//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { FindManyArgs as $FindManyArgs, FindUniqueArgs as $FindUniqueArgs, FindFirstArgs as $FindFirstArgs, ExistsArgs as $ExistsArgs, CreateArgs as $CreateArgs, CreateManyArgs as $CreateManyArgs, CreateManyAndReturnArgs as $CreateManyAndReturnArgs, UpdateArgs as $UpdateArgs, UpdateManyArgs as $UpdateManyArgs, UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs, UpsertArgs as $UpsertArgs, DeleteArgs as $DeleteArgs, DeleteManyArgs as $DeleteManyArgs, CountArgs as $CountArgs, AggregateArgs as $AggregateArgs, GroupByArgs as $GroupByArgs, WhereInput as $WhereInput, SelectInput as $SelectInput, IncludeInput as $IncludeInput, OmitInput as $OmitInput, QueryOptions as $QueryOptions } from "@zenstackhq/orm";
import type { SimplifiedPlainResult as $Result, SelectIncludeOmit as $SelectIncludeOmit } from "@zenstackhq/orm";
export type BoardFindManyArgs = $FindManyArgs<$Schema, "Board">;
export type BoardFindUniqueArgs = $FindUniqueArgs<$Schema, "Board">;
export type BoardFindFirstArgs = $FindFirstArgs<$Schema, "Board">;
export type BoardExistsArgs = $ExistsArgs<$Schema, "Board">;
export type BoardCreateArgs = $CreateArgs<$Schema, "Board">;
export type BoardCreateManyArgs = $CreateManyArgs<$Schema, "Board">;
export type BoardCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "Board">;
export type BoardUpdateArgs = $UpdateArgs<$Schema, "Board">;
export type BoardUpdateManyArgs = $UpdateManyArgs<$Schema, "Board">;
export type BoardUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "Board">;
export type BoardUpsertArgs = $UpsertArgs<$Schema, "Board">;
export type BoardDeleteArgs = $DeleteArgs<$Schema, "Board">;
export type BoardDeleteManyArgs = $DeleteManyArgs<$Schema, "Board">;
export type BoardCountArgs = $CountArgs<$Schema, "Board">;
export type BoardAggregateArgs = $AggregateArgs<$Schema, "Board">;
export type BoardGroupByArgs = $GroupByArgs<$Schema, "Board">;
export type BoardWhereInput = $WhereInput<$Schema, "Board">;
export type BoardSelect = $SelectInput<$Schema, "Board">;
export type BoardInclude = $IncludeInput<$Schema, "Board">;
export type BoardOmit = $OmitInput<$Schema, "Board">;
export type BoardGetPayload<Args extends $SelectIncludeOmit<$Schema, "Board", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "Board", Args, Options>;
export type ColumnFindManyArgs = $FindManyArgs<$Schema, "Column">;
export type ColumnFindUniqueArgs = $FindUniqueArgs<$Schema, "Column">;
export type ColumnFindFirstArgs = $FindFirstArgs<$Schema, "Column">;
export type ColumnExistsArgs = $ExistsArgs<$Schema, "Column">;
export type ColumnCreateArgs = $CreateArgs<$Schema, "Column">;
export type ColumnCreateManyArgs = $CreateManyArgs<$Schema, "Column">;
export type ColumnCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "Column">;
export type ColumnUpdateArgs = $UpdateArgs<$Schema, "Column">;
export type ColumnUpdateManyArgs = $UpdateManyArgs<$Schema, "Column">;
export type ColumnUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "Column">;
export type ColumnUpsertArgs = $UpsertArgs<$Schema, "Column">;
export type ColumnDeleteArgs = $DeleteArgs<$Schema, "Column">;
export type ColumnDeleteManyArgs = $DeleteManyArgs<$Schema, "Column">;
export type ColumnCountArgs = $CountArgs<$Schema, "Column">;
export type ColumnAggregateArgs = $AggregateArgs<$Schema, "Column">;
export type ColumnGroupByArgs = $GroupByArgs<$Schema, "Column">;
export type ColumnWhereInput = $WhereInput<$Schema, "Column">;
export type ColumnSelect = $SelectInput<$Schema, "Column">;
export type ColumnInclude = $IncludeInput<$Schema, "Column">;
export type ColumnOmit = $OmitInput<$Schema, "Column">;
export type ColumnGetPayload<Args extends $SelectIncludeOmit<$Schema, "Column", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "Column", Args, Options>;
export type TaskFindManyArgs = $FindManyArgs<$Schema, "Task">;
export type TaskFindUniqueArgs = $FindUniqueArgs<$Schema, "Task">;
export type TaskFindFirstArgs = $FindFirstArgs<$Schema, "Task">;
export type TaskExistsArgs = $ExistsArgs<$Schema, "Task">;
export type TaskCreateArgs = $CreateArgs<$Schema, "Task">;
export type TaskCreateManyArgs = $CreateManyArgs<$Schema, "Task">;
export type TaskCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "Task">;
export type TaskUpdateArgs = $UpdateArgs<$Schema, "Task">;
export type TaskUpdateManyArgs = $UpdateManyArgs<$Schema, "Task">;
export type TaskUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "Task">;
export type TaskUpsertArgs = $UpsertArgs<$Schema, "Task">;
export type TaskDeleteArgs = $DeleteArgs<$Schema, "Task">;
export type TaskDeleteManyArgs = $DeleteManyArgs<$Schema, "Task">;
export type TaskCountArgs = $CountArgs<$Schema, "Task">;
export type TaskAggregateArgs = $AggregateArgs<$Schema, "Task">;
export type TaskGroupByArgs = $GroupByArgs<$Schema, "Task">;
export type TaskWhereInput = $WhereInput<$Schema, "Task">;
export type TaskSelect = $SelectInput<$Schema, "Task">;
export type TaskInclude = $IncludeInput<$Schema, "Task">;
export type TaskOmit = $OmitInput<$Schema, "Task">;
export type TaskGetPayload<Args extends $SelectIncludeOmit<$Schema, "Task", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "Task", Args, Options>;
